apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: chart06-appset
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/mteodor/helm-charts06
        revision: HEAD
        directories:
          - path: charts/*
  template:
    metadata:
      name: '{{.path.basename}}-01'
    spec:
      project: 3eb96a4d
      source:
        repoURL: https://github.com/mteodor/helm-charts06
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        name: cluster11
        namespace: '{{.path.basename}}-06'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true